### ISSUE TITLE
Debugger weiter nach hinten, um ihn an einem komplizierteren, sinnvoll  debugbaren Programm anzuwenden

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhysInfo/Programmiervorkurs#1]
Ideen hierzu: 
- Schleife, die erst im 3. oder 4. Durchlauf Fehler wirft
- Sideeffects, die den Zähler resetten
- Division durch Null, irgendwas…
- ansonsten nutzt man den nicht, weils bei ersten Mal langweilig war
- der tut ja nix, was irgendwie sinnvoll ist

**Comment by wipplingermax** [comment]
Gelöst mit 2dc2a19
