### ISSUE TITLE
Kapitel 2 """überarbeiten"""

### ISSUE THREAD

**Issue by jenuk** [FachschaftMathPhysInfo/Programmiervorkurs#103]
Zurzeit besteht das zweite Kapitel aus nur drei kurzen, mehr oder weniger fertigen Lektionen, die leider auch nur wenig zusammenhängend sind. Ich möchte das ganze gerne etwas vervollständigen und vielleicht auch versuchen einen roten Faden reinzubringen mit einem netten Abschluss wie in Kapitel 1.

**Comment by fschledorn** [comment]
Nach 3 Jahren ist das dann eine gute Gelegenheit nochmal allgemein über Kapitel 2 zu sprechen und es entweder grundlegend zu überarbeiten oder zu streichen.

**Comment by fschledorn** [comment]
Kapitel wursche gelöscht
