### ISSUE TITLE
Titlesec und Komascript sind inkompatibel

### ISSUE THREAD

**Issue by jenuk** [FachschaftMathPhysInfo/Programmiervorkurs#105]
Prinzipiell sollten neue Versionen von dem Paket `titlesec` und Koma-Klassen nicht mehr kompatibel sein, siehe z.B. hier dieses Issue bei titlesec: https://github.com/jbezos/titlesec/issues/22, oder die bekannten Probleme von Koma https://komascript.de/release3.27

Der Log sagt bei mir dazu:
```
Class scrbook Info: Unknown `titesec' release.
(scrbook)           Cross your fingers, that is compatible on input line 10.
```

Und wir scheinen hier tatsächlich noch Glück zu haben (zumindest bei mir mit TeX Live 2019): Diese Zeile hier sorgt scheinbar aktuell dafür, dass `\section` noch benutzbar ist. 
https://github.com/FachschaftMathPhysInfo/Programmiervorkurs/blob/6ffa96b9b8469d91d15b1e7059cd89009e947dbf/vorkurs.cls#L34
Zumindest kompiliert das Skript nicht mehr -- mit der gleichen Fehlermeldung wie in dem verlinkten Issue -- wenn man diese Zeile entfernt.
Außerdem kommt es zum gleichen Fehler, wenn man eine `\subsection` hinzufügt.

Ich würde vorschlagen, dass wir auf Dauer nicht darauf hoffen, dass es schon weiterhin gut geht; beide Autoren hören sich nicht so an als würden sie irgendwie darauf achten in der Zukunft. Ich sehe diese beiden Möglichkeiten damit umzugehen:
1. Rauswerfen von titlesec: Dann müsste man sich anschauen, wie man die Formatierung der Sections und Kapiteln anpassen will, die laufen soweit ich das gerade sehen kann über titlesec. (Das wäre auch relevant für #26)
2. Hinzufügen von `\usepackage[standardsections]{scrhack}`. Dazu steht bei den Release-Notes von Komascript:
> Achtung: Dieser Hack kann eine Menge zerstören! Es gibt keinen Support für Probeme bei dessen Verwendung! Dieser Hack ist ab KOMA-Script 3.27.3173 verfügbar

**Comment by jenuk** [comment]
Und wenn dann irgendwann `vorkurs.cls` aufgeräumt wird, kann man auch darüber nachdenken, `fancyhdr` zu ersetzen, was auch nicht gerne mit Koma-Klassen arbeitet, im Log steht bei mir dazu folgendes:
```
Class scrbook Warning: Usage of package `fancyhdr' together
(scrbook)              with a KOMA-Script class is not recommended.
(scrbook)              I'd suggest to use 
(scrbook)              package `scrlayer' or `scrlayer-scrpage', because
(scrbook)              they support KOMA-Script classes.
(scrbook)              With `fancyhdr' several features of class `scrbook'
(scrbook)              like options `headsepline', `footsepline' or command
(scrbook)              `\MakeMarkcase' and the commands `\setkomafont' and
(scrbook)              `\addtokomafont' for the page style elements need
(scrbook)              explicite user intervention to work.
(scrbook)              Nevertheless, using requested
(scrbook)              package `fancyhdr' on input line 9.
```

**Comment by fschledorn** [comment]
I think the issue is closed, at least it is still compiling without issues 3 years later so it ain’t that much of a problem rn
