### ISSUE TITLE
Praxis in Lektion 14 "Die C++ Standardbibliothek" doppelt

### ISSUE THREAD

**Issue by jenuk** [FachschaftMathPhysInfo/Programmiervorkurs#120]
In der Datei `stdbib.tex` scheint beim mergen die Praxis verdoppelt worden zu sein. Die eine Kopie sollte man löschen.

https://github.com/FachschaftMathPhysInfo/Programmiervorkurs/blob/7c97a3a7c738204907083c303eca8b8a6a1b7b8e/basics/stdbib.tex#L53-L83

**Comment by fschledorn** [comment]
Das Problem ist immer noch da. Bei der Revision jetzt für den Programmiervorkurs für das Wise24/25 sollte das beachtet werden
