### ISSUE TITLE
Feedback aus der Google Umfrage auswerten und passende Issues erstellen

### ISSUE THREAD

**Issue by fschledorn** [FachschaftMathPhysInfo/Programmiervorkurs#131]

**Comment by calvalre** [comment]
ihr könnt zeitgleich das feedback aus dem öffentlichen hedgedoc (https://hedgedoc.mathphys.info/programmiervorkurs-kritik) als auch dem privaten (https://hedgedoc.mathphys.info/programmiervorkurs-nachbesprechung) einarbeiten

**Comment by Xeldlie** [comment]
Feedback von hier nehmen: https://hedgedoc.mathphys.info/programmiervorkurs-nachbesprechung?view

**Comment by Plebysnacc** [comment]
this done?
