### ISSUE TITLE
Lektion 12: style

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhysInfo/Programmiervorkurs#14]
- Vielleicht früher einführen, damit Leute dann schönen Code schreiben.

**Comment by friedz** [comment]
solange nicht alle Konzepte eingeführt sind natürlich schwierig.
Wir könnten aber natürlich auch jedes mal wenn Dinge wie `if else` oder `while` eingeführt werden einen Satz dazu schreiben wie diese zu formatieren sind :+1:

**Comment by TomTomRixRix** [comment]
Ich habe mal in den Lektionen zum Kontrollfluss und zu Schleifen ein/zwei Sätze hinzugefügt, dass man Blöcke einrücken sollte und einen Verweis auf die `coding style` Lektion eingefügt. In der Lektion habe ich dann noch etwas ausführlicher erklärt, was die Motivation hinter dem Einrücken und anderen coding style Maßnahmen ist.

Sicherlich könnte man noch früher mit coding style anfangen, aber ich denke, man sollte erst einmal die Basics gelernt haben und sich dann Gedanken um den coding style machen. Die Programme der ersten 8 Lektionen sind auch nicht so super komplex, dass sie unlesbar werden. Allerdings finde ich auch, dass man mit der Einführung von bedingten Anweisungen auch lernen sollte, seinen Code schön zu formattieren, damit er lesbar bleibt. Das sollte jetzt das Skript auch erfüllen.
