### ISSUE TITLE
Confusing words 

### ISSUE THREAD

**Issue by Xeldlie** [FachschaftMathPhysInfo/Programmiervorkurs#150]
Note all words that require a definition here: #149

**Comment by fschledorn** [comment]
Shouldn’t this be combined with the glossary idea from Tom Rix (see #93  and #101) and the Diskussion #149 or is there a particular reason for opening both a Diskussion and an Issue? All of these Ideas could be effectively solved by implementing a good glossary where words and concepts are explained more in detail.

**Comment by Xeldlie** [comment]
Very good point, I'll close this issue and add the discussion link to the glossary issue #93
