### ISSUE TITLE
Weitere Gedanken zu Kapitel 1

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhysInfo/Programmiervorkurs#20]
Eventuell könnte man Kapitel 1 um Pointer erweitern und eine Lektion 20
schreiben.
- Aufgabe, die Eigenheiten von pointern zeigt und wenig fehleranfällig ist und erklärt was passiert (Funktion, die sideeffects über pointer hat oder so)
- Aufgabe, die fehler zeigt, wo man von pointern verwirrt ist und so…
- Arrays sind pointer, pointerarithmetik, speichergrenzen->spiel
- eventuell mit sizeof() arbeiten? (scoping and shit)
- Referenzen? eher nicht, lieber pointer

Dann müsste man vielleicht nach Lektion 20 noch mal ein cooles Programm schreiben, das einen allumfassenden abschluss macht

**Comment by koebi** [comment]
Hier sollte man auf jeden Fall zu erst erklären, was stack und heap sind, und wozu man pointer denn dann braucht (eben um returns auf dem heap zu speichern)

**Comment by friedz** [comment]
ich glaube es wäre besser carrays komplett durch std::vector ersetzen da treten so sideeffects nicht auf
und Pointer dann sinnvoll in einem späteren Kapitel erklären

**Comment by wipplingermax** [comment]
In der Überabeitung sind wir zu dem Schluss gekommen, dass die Konzepte von Pointer, Heap und Stack im Rahmen des Vorkurses zuweit führen. Carrays wurden bereits durch Vektoren ersetzt. Entsprechend wird das Issue geschlossen.
