### ISSUE TITLE
link zu lektionen enden ein Stück unter der Überschrift

### ISSUE THREAD

**Issue by friedz** [FachschaftMathPhysInfo/Programmiervorkurs#26]
die Links  zu den einezelnen lektionen gehen immer zur letzen zeile oder so von der lektion davor wobei dann meist noch eine halbe seite oder so danach lehr ist (das ist verdammt hässlich)

**Comment by friedz** [comment]
endet jetzt an Sinnvollen stellen kann aber noch schöner gemacht werden

**Comment by TheEbolaDoc** [comment]
Hmpf, das ist immer noch nicht so wirklich toll, aber ich bin leider nicht TeXnik versiert genug das zu fixen :disappointed: 
@TomTomRixRix for the rescue? :100: :fire:

**Comment by TomTomRixRix** [comment]
Das ist in der Tat gar nicht so einfach, aber mit etwas TeX Magie klappt es. Das Problem ist, dass die Überschriften der Lektionen Sections sind, die ja aber nicht wie beim Standardlayout auf der Seite vor dem entsprechenden Text stehen, sondern im header. Deshalb ist die Position, auf die der Link verweist, direkt unterhalb des Headers. Was man aber möchte - zumindest unterstelle ich das mal - ist, dass der Link auf den Seitenanfang verweist. Sodass man den kompletten Header noch lesen kann.

Um dieses Verhalten zu erzeugen, kann man in der `vorkurs.cls` Datei Zeile 36 ändern in:

```TeX
\newcommand{\lesson}[1]{\clearpage \vspace*{-42mm} \section{#1} \vspace*{29.5mm}\renewcommand{\myrightmark}{#1}}
```

Was da passiert ist letztendlich nur ein simples *gehe 42 😄 mm hoch, setzte dort den section Anker und gehe wieder 29.5 mm runter*. Die Werte habe ich manuell bestimmt, ich hoffe, dass sie auch bei anderen Setups funktionieren. 

Die Lösung ist zwar nicht schön, sondern ein hässlicher workaround, aber sie sollte das gewünschte Verhalten und nicht all zu viele Probleme in Zukunft erzeugen.

**Comment by TomTomRixRix** [comment]
Den quickfix workaround habe ich mal umgesetzt. Da langfristig ohnehin eine andere/bessere Lösung her muss, wie in #105 beschrieben, sollte das fürs erste passen und sich dann eh erübrigen.
