### ISSUE TITLE
Test-Teil

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhysInfo/Programmiervorkurs#56]
Gegebenenfalls könnte man hinter den "Spiel"-Teil jeder Lektion einen Test-Teil einfügen, wo die Leute an zwei, drei einfachen Fragen nochmal gucken können, ob sie alles verstanden haben.

**Comment by friedz** [comment]
Finde ich nicht so Schön.

**Comment by friedz** [comment]
was man aber machen könnte ist, einfache Testcases, alla `assert( )` recht früh ein zu führen und ab dann einen kleine Teil zum Testen des Codes:
+ Überleg dier wie du das bisherige Programm Testen Kannst
+ Schreibe ein Paar Test (auch für deine Änderungen)

Das Prüft im Prinzip auch ob sie verstanden haben was sie tun, fühlt sich aber  vermutlich mehr an als ob sie sich selbst und vor allem auch uns überprüfen ob wir alles richtig gemacht haben :sparkles:.
