### ISSUE TITLE
Lektion 2: Shell

### ISSUE THREAD

**Issue by jenuk** [FachschaftMathPhysInfo/Programmiervorkurs#77]
Beim ls long listing format hat jeder Ordner die gleiche Größe, man sollte darauf achten, dass die Erstis das in einem Ordner ohne Unterordner ausführen oder es erklären. Was haltet ihr davon?

Außerdem sollte in einem weiteren Spiel Teil tab und die history erklären bzw rausfinden lassen wie das funktioniert.

**Comment by friedz** [comment]
`tab` und history sind #51 und zu dem "long listing format" sollte sowieso noch dazu das man mit `/` in manpages suchen kann

zu der Ordner Größe wäre es vielleicht schön eine Frage noch zu stellen die schon auf die Antwort hin deutet
