### ISSUE TITLE
Lektion 01

### ISSUE THREAD

**Issue by jenuk** [FachschaftMathPhysInfo/Programmiervorkurs#83]
Angeblich steht im Skript etwas anderes als was da wirklich passiert

**Comment by jenuk** [comment]
Ich meine das Problem hier war, dass im Text steht "wir führen zuerst `g++ -o outputDatei` und dann `./outout`." und dann steht da das Diagramm soll das nochmal übersichtlich machen. Das hat dann aber nicht das aus dem Text im Inhalt wie es vorher steht, sondern ist Praxis 3 & 4.

Ich bin mir nicht sicher wie man das am besten fixt, denn zum Diagramm gehört ja schon, dass es am Ende auch ein Output da ist, aber ich weiß nicht wei man einen Output für ein beliebiges Programm darstellt. In der aktuellen Version steht als Outut einfach der konkrete Output aus der Praxis.

**Comment by wipplingermax** [comment]
Erledigt :)
