### ISSUE TITLE
Terminal Befehle setzen

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhysInfo/Programmiervorkurs#91]
Man sollte vielleicht Befehle fürs Terminal anders setzen als C++ Code, damit die Studis direkt wissen, was sie ins Terminal eingeben und was in ihren Editor. Zum Beispiel die Terminal Befehle schwarz hinterlegen in grüner Schrift ;)

**Comment by jenuk** [comment]
Das klingt nach einer guten Idee. Ich wäre allerdings gegen eine grüne Schrift. Würde eher Weiß auf Schwarz benutzen.

Ansonsten hätte ich noch diese Fragen zu der Idee:
- Wie sieht es mit der `.sh` in Kapitel 2 aus? Soll das auch ein riesiger schwarzer Block werden? Ist vielleicht ungeil beim Drucken, aber eigentlich wird das ja eh nicht wirklich gedruckt.
- Was ist mit Dateinamen/Ordnernamen, aktuell sind die einfach als typewriter gesetzt. Ich könnte mir vorstellen, dass es hier nett wäre die auch ein bisschen abzuheben, aber ich würde sie nicht wie Befehle setzen.
- Soll das auch so gemacht werden, wenn Programme in einem Satz erwähnt werden, die theoretisch auch Konsolen-Befehle sind? Zum Beispiel: (Lektion 1)
  > Nachdem `g++` uns also ein Maschinencodefile `outputDatei` erzeugt hat, können wir es zur Ausführung bringen.

  Hier bin ich mir unsicher. Ich würde das vermutlich als Befehl setzen.

**Comment by TomTomRixRix** [comment]
In Vorbereitung auf den nächsten Programmiervorkurs habe ich mir mal Gedanken zu den Fragen gemacht:

* Weiße Schrift vor schwarzem Hintergrund ist glaube ich eh besser. Aber das kann ja ein Parameter sein, den man schnell anpassen kann, wenn man unbedingt will ;)

*  Ich würde glaube ich die Befehle nicht als Code-Block setzen (klar, man kann die `basics.sh` Datei auch als Shell-Skript ausführen, aber der Fokus in der Lektion liegt ja erstmal darauf, dass die Befehle einzeln nacheinander ins Terminal eingegeben werden). Stattdessen würde ich die Befehle als Auflistung setzen (entweder hintereinander kommasepariert oder untereinander, da bin ich mir noch nicht sicher) und dort aber wie vorgeschlagen mit weißer monospace font vor schwarzem Hintergrund.

* Dateinamen/Ordnernamen würde ich auch nicht wie Befehle setzen, außer sie sind natürlich Teil eines Befehls (`g++ meinProgramm.cpp -o outputDatei`). Ich finde, dass wenn die Dateinamen/Ordnernamen als typewriter gesetzt sind, das eigentlich ausreichen sollte. Aber man kann sie gerne noch in einer anderen Farbe hervorheben oder fett setzen.

* Da man `g++` ins Terminal eingibt, würde ich das auch als Befehl setzen. Genau so bei `gdb` 

In der Tat müsste man mal das ganze Dokument durchgehen. Dabei könnte man auch gleich mal Rechtschreibung und Kommasetzung checken.
